AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/NumericLiterals:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 50

Style/SingleLineMethods:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
