AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/shared/*'
    - 'spec/unit/client_spec.rb' # TODO: Parsing error. Fix later.

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/NumericLiterals:
  Enabled: false

Style/DateTime:
  Enabled: false
