version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rspec

  publish_release_production:
    docker:
      - image: circleci/ruby:2.4.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh release.sh


workflows:
  version: 2
  continuous_delivery:
    jobs:
      - build
      - hold_publish_release_production:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - publish_release_production:
          requires:
            - hold_publish_release_production
